version: 0
os: linux
files:
  - source: /
    destination: /home/ec2-user/inx-front
permissions:
  - object: /home/ec2-user
    mode: 774
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: codedeploy_scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy_scripts/post_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: codedeploy_scripts/run.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: codedeploy_scripts/stop.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: codedeploy_scripts/validate.sh
      timeout: 60
      runas: ec2-user
